/**
 * Level data for Mario Adventure.
 * Each level is 15 rows tall. Tile legend:
 *   ' ' = air, '#' = solid, 'B' = brick, '?' = coin block,
 *   '!' = power-up block, '-' = one-way platform, '^' = hazard, 'C' = coin
 * Enemies, player start, and flag are defined separately.
 */

/* eslint-disable comma-spacing */
const LEVELS = [
  // ===== LEVEL 1: GREEN HILLS =====
  {
    name: 'Green Hills',
    subtitle: 'Learn the basics!',
    powerUpType: 'speed',
    powerUpName: 'Speed Mushroom',
    bg: { sky1: '#5c94fc', sky2: '#87CEEB', hill: '#2d8b2d', ground: '#c84c0c', groundTop: '#4abe4a' },
    playerStart: { x: 3, y: 11 },
    flagPos: { x: 93, y: 3 },
    enemies: [
      { type: 'goomba', x: 15, y: 12 },
      { type: 'goomba', x: 22, y: 12 },
      { type: 'goomba', x: 38, y: 12 },
      { type: 'koopa',  x: 50, y: 11 },
      { type: 'goomba', x: 58, y: 12 },
      { type: 'goomba', x: 65, y: 12 },
      { type: 'koopa',  x: 75, y: 11 },
      { type: 'goomba', x: 82, y: 12 },
    ],
    tileMap: [
      //0         1         2         3         4         5         6         7         8         9
      //0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456
      '                                                                                                ',
      '                                                                                                ',
      '                                                                                                ',
      '                                                                                           T    ',
      '                                                                                           F    ',
      '                                                                                           F    ',
      '                  C C C                          C   C                  C C C                F    ',
      '                 ?B!B?                  ---     ---                    ?B?B?                 F    ',
      '                                                          C C C                             F    ',
      '            C                 ---                ---      -----              ---            F    ',
      '           ---                                                                             F    ',
      '                                                                                      ##   F    ',
      '                                  C C                                            ##   ##   F    ',
      '################  ####   #####  ########   ######   ##########  #####  ######  ########  #######',
      '################  ####   #####  ########   ######   ##########  #####  ######  ########  #######',
    ],
  },

  // ===== LEVEL 2: UNDERGROUND CAVE =====
  {
    name: 'Underground Cave',
    subtitle: 'Watch out for the dark!',
    powerUpType: 'highjump',
    powerUpName: 'Spring Boots',
    bg: { sky1: '#1a1a2e', sky2: '#16213e', hill: '#2a2a4a', ground: '#5a4a3a', groundTop: '#8a7a6a' },
    playerStart: { x: 3, y: 11 },
    flagPos: { x: 88, y: 3 },
    enemies: [
      { type: 'goomba', x: 12, y: 12 },
      { type: 'goomba', x: 18, y: 12 },
      { type: 'koopa',  x: 28, y: 11 },
      { type: 'goomba', x: 35, y: 12 },
      { type: 'goomba', x: 42, y: 8 },
      { type: 'koopa',  x: 55, y: 11 },
      { type: 'goomba', x: 62, y: 12 },
      { type: 'goomba', x: 70, y: 12 },
      { type: 'koopa',  x: 78, y: 11 },
    ],
    tileMap: [
      '                                                                                            ',
      '                                                                                            ',
      '                                                                                            ',
      '                                                                                       T    ',
      '                                    #                                                   F    ',
      '    C                               #   C C C                     C                     F    ',
      '   BBB        C C       ---         #  B?B?B        ---          ---          C C       F    ',
      '             -----                  #                                        -----      F    ',
      '                          C C       #          C         C C                            F    ',
      '         C       ---     -----      #   ---   ---       -----       ---    ---     ##   F    ',
      '        ---                                                                        ##   F    ',
      '                    C                                C                          #  ##   F    ',
      '             ##    ###          !          ---       ---       C    ##    ##   ####  #####    ',
      '######  ####  ##  ##### ######  ######  #######  ########  ######  ###  ####  ##########    #',
      '######  ####  ##  ##### ######  ######  #######  ########  ######  ###  ####  ##########    #',
    ],
  },

  // ===== LEVEL 3: CLOUD KINGDOM =====
  {
    name: 'Cloud Kingdom',
    subtitle: "Don't look down!",
    powerUpType: 'shield',
    powerUpName: 'Star Shield',
    bg: { sky1: '#87CEEB', sky2: '#E0F0FF', hill: '#ddd', ground: '#f0f0f0', groundTop: '#ffffff' },
    playerStart: { x: 3, y: 11 },
    flagPos: { x: 95, y: 3 },
    enemies: [
      { type: 'goomba', x: 14, y: 8 },
      { type: 'koopa',  x: 22, y: 6 },
      { type: 'goomba', x: 30, y: 10 },
      { type: 'goomba', x: 40, y: 8 },
      { type: 'koopa',  x: 50, y: 6 },
      { type: 'goomba', x: 58, y: 10 },
      { type: 'goomba', x: 66, y: 8 },
      { type: 'koopa',  x: 74, y: 6 },
      { type: 'goomba', x: 82, y: 10 },
      { type: 'goomba', x: 88, y: 8 },
    ],
    tileMap: [
      '                                                                                                 ',
      '                                                                                                 ',
      '                                                                                                 ',
      '                                                                                            T    ',
      '                                                                                            F    ',
      '          C C C            C C C              C C C            C C C            C C C        F    ',
      '         -------    !    -------            -------    ?     -------          -------        F    ',
      '                  ---                     C          ---                   C            ##   F    ',
      '    C C         C     C        C C       ---   C          C       C C     ---          ##   F    ',
      '   -----  ?   -----  ---      -----           ---   ?   -----   -----           ?     ##   F    ',
      '                                    C                                C                 ##   F    ',
      '                                   ---                              ---                ##   F    ',
      '###                                                                                    ##  F    ',
      '###                                                                                   ########  ',
      '###              ^^          ^^            ^^          ^^            ^^                 ########  ',
    ],
  },

  // ===== LEVEL 4: FROZEN PEAKS =====
  {
    name: 'Frozen Peaks',
    subtitle: 'Slippery ice ahead!',
    powerUpType: 'rapidice',
    powerUpName: 'Ice Storm',
    bg: { sky1: '#4a6fa5', sky2: '#c8d8e8', hill: '#8aabc4', ground: '#6090b0', groundTop: '#c8e8ff' },
    playerStart: { x: 3, y: 11 },
    flagPos: { x: 98, y: 3 },
    enemies: [
      { type: 'goomba', x: 14, y: 12 },
      { type: 'koopa',  x: 22, y: 11 },
      { type: 'goomba', x: 30, y: 12 },
      { type: 'koopa',  x: 38, y: 11 },
      { type: 'goomba', x: 48, y: 8 },
      { type: 'goomba', x: 55, y: 12 },
      { type: 'koopa',  x: 62, y: 11 },
      { type: 'goomba', x: 70, y: 12 },
      { type: 'goomba', x: 78, y: 12 },
      { type: 'koopa',  x: 85, y: 11 },
      { type: 'goomba', x: 90, y: 12 },
    ],
    tileMap: [
      '                                                                                                    ',
      '                                                                                                    ',
      '                                                                                                    ',
      '                                                                                               T    ',
      '                                                C                                               F    ',
      '                   C C C          C C          ---              C C C                            F    ',
      '                  B?!?B          -----                C       B?B?B         C C                 F    ',
      '                                          C          ---                   -----                F    ',
      '            C           ---      ---      ---                                        C     ##   F    ',
      '     C     ---                                   C       ---        C C     ---      ---   ##   F    ',
      '    ---                      C                  ---                -----                    ##   F    ',
      '                            ---         C                                              #   ##   F    ',
      '                                       ---           C                           ##   ##   ##  F    ',
      '##############  #####  ########  ########   ######  ######  ########  ######  ##############  ####',
      '##############  #####  ########  ########   ######  ######  ########  ######  ##############  ####',
    ],
  },

  // ===== LEVEL 5: BOWSER'S CASTLE =====
  {
    name: "Bowser's Castle",
    subtitle: 'The final challenge!',
    powerUpType: 'giant',
    powerUpName: 'Mega Mushroom',
    bg: { sky1: '#1a0505', sky2: '#3a1515', hill: '#4a2020', ground: '#5a3030', groundTop: '#8a5050' },
    playerStart: { x: 3, y: 11 },
    flagPos: { x: 108, y: 3 },
    enemies: [
      { type: 'goomba', x: 12, y: 12 },
      { type: 'koopa',  x: 18, y: 11 },
      { type: 'goomba', x: 25, y: 12 },
      { type: 'goomba', x: 32, y: 8 },
      { type: 'koopa',  x: 38, y: 11 },
      { type: 'goomba', x: 45, y: 12 },
      { type: 'koopa',  x: 52, y: 11 },
      { type: 'goomba', x: 58, y: 12 },
      { type: 'goomba', x: 64, y: 8 },
      { type: 'koopa',  x: 72, y: 11 },
      { type: 'goomba', x: 78, y: 12 },
      { type: 'goomba', x: 85, y: 12 },
      { type: 'koopa',  x: 92, y: 11 },
      { type: 'goomba', x: 98, y: 12 },
    ],
    tileMap: [
      '                                                                                                              ',
      '                                                                                                              ',
      '                                                                                                              ',
      '                                                                                                         T    ',
      '                                  #               #                                                       F    ',
      '            C C        C C        #    C C C      #           C C           C C C                          F    ',
      '           B?B?B      B!B?B       #   ?B?B?       #          -----         B?B!B?       C C               F    ',
      '                                  #               #    C               C                -----              F    ',
      '      C          ---         C    #   ---    ---  #   ---         ---  C          C              ##   ##   F    ',
      '     ---   C          ---   ---   #               #                  ---   ---   ---    ---  ##  ##   ##   F    ',
      '          ---                     #          C    #       C                                  ##  ##   ##   F    ',
      '                     C           ^^         ---  ^^      ---                       #    ##   ##  ##   ##   F    ',
      '               ##   ---     ##  ^^^^   ##       ^^^^  ##      C    ##    ##   ##  ##   ##   ##  ##   ## ####',
      '####  ######  ####  ###  ###### ###### ######  ###### ####  ####  ####  ####  ######  ###  ######  #########',
      '####  ######  ####  ###  ###### ###### ######  ###### ####  ####  ####  ####  ######  ###  ######  #########',
    ],
  },
];
