const LEVELS = [
  {
    id: 1,
    title: 'Route 1',
    subtitle: 'Easy Start!',
    description: '×1 and ×2',
    factors: [1, 2],
    maxOperand: 10,
    rounds: 8,
    coinsPerCorrect: 2,
    bonusCoins: 5,
    battleAfter: true,
    theme: 'grass',
  },
  {
    id: 2,
    title: 'Route 2',
    subtitle: 'Getting Stronger!',
    description: '×3 and ×4',
    factors: [3, 4],
    maxOperand: 10,
    rounds: 8,
    coinsPerCorrect: 2,
    bonusCoins: 5,
    battleAfter: false,
    theme: 'grass',
  },
  {
    id: 3,
    title: 'Route 3',
    subtitle: 'High Fives!',
    description: '×5 tables',
    factors: [5],
    maxOperand: 12,
    rounds: 8,
    coinsPerCorrect: 3,
    bonusCoins: 8,
    battleAfter: true,
    theme: 'water',
  },
  {
    id: 4,
    title: 'Route 4',
    subtitle: 'Double Trouble!',
    description: '×6 and ×7',
    factors: [6, 7],
    maxOperand: 10,
    rounds: 10,
    coinsPerCorrect: 3,
    bonusCoins: 8,
    battleAfter: false,
    theme: 'fire',
  },
  {
    id: 5,
    title: 'Route 5',
    subtitle: 'Power Up!',
    description: '×8 and ×9',
    factors: [8, 9],
    maxOperand: 10,
    rounds: 10,
    coinsPerCorrect: 4,
    bonusCoins: 10,
    battleAfter: true,
    theme: 'electric',
  },
  {
    id: 6,
    title: 'Route 6',
    subtitle: 'Perfect Tens!',
    description: '×10 tables',
    factors: [10],
    maxOperand: 15,
    rounds: 8,
    coinsPerCorrect: 3,
    bonusCoins: 8,
    battleAfter: false,
    theme: 'water',
  },
  {
    id: 7,
    title: 'Route 7',
    subtitle: 'Beyond!',
    description: '×11 and ×12',
    factors: [11, 12],
    maxOperand: 12,
    rounds: 10,
    coinsPerCorrect: 4,
    bonusCoins: 12,
    battleAfter: true,
    theme: 'psychic',
  },
  {
    id: 8,
    title: 'Route 8',
    subtitle: 'Expert!',
    description: '×13 and ×14',
    factors: [13, 14],
    maxOperand: 10,
    rounds: 10,
    coinsPerCorrect: 5,
    bonusCoins: 15,
    battleAfter: true,
    theme: 'ghost',
  },
  {
    id: 9,
    title: 'Route 9',
    subtitle: 'Ultimate!',
    description: '×15 tables',
    factors: [15],
    maxOperand: 15,
    rounds: 10,
    coinsPerCorrect: 5,
    bonusCoins: 15,
    battleAfter: true,
    theme: 'dragon',
  },
  {
    id: 10,
    title: 'Pokemon League',
    subtitle: 'Final Challenge!',
    description: 'All tables mixed!',
    factors: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
    maxOperand: 15,
    rounds: 15,
    coinsPerCorrect: 5,
    bonusCoins: 25,
    battleAfter: true,
    theme: 'dragon',
  },
];
