const LEVELS = [
  {
    id: 1,
    title: 'Route 1',
    subtitle: 'Easy Start!',
    description: '×1 and ×2',
    factors: [1, 2],
    maxOperand: 10,
    rounds: 8,
    coinsPerCorrect: 1,
    bonusCoins: 2,
    battleAfter: true,
    theme: 'grass',
  },
  {
    id: 2,
    title: 'Route 2',
    subtitle: 'Getting Stronger!',
    description: '×3 and ×4',
    factors: [3, 4],
    maxOperand: 10,
    rounds: 8,
    coinsPerCorrect: 1,
    bonusCoins: 2,
    battleAfter: false,
    theme: 'grass',
  },
  {
    id: 3,
    title: 'Route 3',
    subtitle: 'High Fives!',
    description: '×5 tables',
    factors: [5],
    maxOperand: 12,
    rounds: 8,
    coinsPerCorrect: 1,
    bonusCoins: 4,
    battleAfter: true,
    theme: 'water',
  },
  {
    id: 4,
    title: 'Route 4',
    subtitle: 'Double Trouble!',
    description: '×6 and ×7',
    factors: [6, 7],
    maxOperand: 10,
    rounds: 10,
    coinsPerCorrect: 1,
    bonusCoins: 4,
    battleAfter: false,
    theme: 'fire',
  },
  {
    id: 5,
    title: 'Route 5',
    subtitle: 'Power Up!',
    description: '×8 and ×9',
    factors: [8, 9],
    maxOperand: 10,
    rounds: 10,
    coinsPerCorrect: 2,
    bonusCoins: 5,
    battleAfter: true,
    theme: 'electric',
  },
  {
    id: 6,
    title: 'Route 6',
    subtitle: 'Perfect Tens!',
    description: '×10 tables',
    factors: [10],
    maxOperand: 15,
    rounds: 8,
    coinsPerCorrect: 2,
    bonusCoins: 4,
    battleAfter: false,
    theme: 'water',
  },
  {
    id: 7,
    title: 'Route 7',
    subtitle: 'Beyond!',
    description: '×11 and ×12',
    factors: [11, 12],
    maxOperand: 12,
    rounds: 10,
    coinsPerCorrect: 2,
    bonusCoins: 6,
    battleAfter: true,
    theme: 'psychic',
  },
  {
    id: 8,
    title: 'Route 8',
    subtitle: 'Expert!',
    description: '×13 and ×14',
    factors: [13, 14],
    maxOperand: 10,
    rounds: 10,
    coinsPerCorrect: 2,
    bonusCoins: 7,
    battleAfter: true,
    theme: 'ghost',
  },
  {
    id: 9,
    title: 'Route 9',
    subtitle: 'Ultimate!',
    description: '×15 tables',
    factors: [15],
    maxOperand: 15,
    rounds: 10,
    coinsPerCorrect: 3,
    bonusCoins: 7,
    battleAfter: true,
    theme: 'dragon',
  },
  {
    id: 10,
    title: 'Pokemon League',
    subtitle: 'Final Challenge!',
    description: 'All tables mixed!',
    factors: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
    maxOperand: 15,
    rounds: 15,
    coinsPerCorrect: 3,
    bonusCoins: 12,
    battleAfter: true,
    theme: 'dragon',
  },
];

// ── Division levels (same factor progression, reversed problems) ──

const LEVELS_DIV = [
  { id: 1, title: 'Route 1', subtitle: 'Easy Split!', description: '÷1 and ÷2', factors: [1, 2], maxOperand: 10, rounds: 8, coinsPerCorrect: 1, bonusCoins: 2, battleAfter: true, theme: 'water' },
  { id: 2, title: 'Route 2', subtitle: 'Fair Shares!', description: '÷3 and ÷4', factors: [3, 4], maxOperand: 10, rounds: 8, coinsPerCorrect: 1, bonusCoins: 2, battleAfter: false, theme: 'grass' },
  { id: 3, title: 'Route 3', subtitle: 'Halves & Fifths!', description: '÷5 tables', factors: [5], maxOperand: 12, rounds: 8, coinsPerCorrect: 1, bonusCoins: 4, battleAfter: true, theme: 'water' },
  { id: 4, title: 'Route 4', subtitle: 'Tricky Splits!', description: '÷6 and ÷7', factors: [6, 7], maxOperand: 10, rounds: 10, coinsPerCorrect: 1, bonusCoins: 4, battleAfter: false, theme: 'fire' },
  { id: 5, title: 'Route 5', subtitle: 'Big Divides!', description: '÷8 and ÷9', factors: [8, 9], maxOperand: 10, rounds: 10, coinsPerCorrect: 2, bonusCoins: 5, battleAfter: true, theme: 'electric' },
  { id: 6, title: 'Route 6', subtitle: 'Perfect Tens!', description: '÷10 tables', factors: [10], maxOperand: 15, rounds: 8, coinsPerCorrect: 2, bonusCoins: 4, battleAfter: false, theme: 'water' },
  { id: 7, title: 'Route 7', subtitle: 'Beyond!', description: '÷11 and ÷12', factors: [11, 12], maxOperand: 12, rounds: 10, coinsPerCorrect: 2, bonusCoins: 6, battleAfter: true, theme: 'psychic' },
  { id: 8, title: 'Route 8', subtitle: 'Expert!', description: '÷13 and ÷14', factors: [13, 14], maxOperand: 10, rounds: 10, coinsPerCorrect: 2, bonusCoins: 7, battleAfter: true, theme: 'ghost' },
  { id: 9, title: 'Route 9', subtitle: 'Ultimate!', description: '÷15 tables', factors: [15], maxOperand: 15, rounds: 10, coinsPerCorrect: 3, bonusCoins: 7, battleAfter: true, theme: 'dragon' },
  { id: 10, title: 'Pokemon League', subtitle: 'Division Master!', description: 'All divisions mixed!', factors: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15], maxOperand: 15, rounds: 15, coinsPerCorrect: 3, bonusCoins: 12, battleAfter: true, theme: 'dragon' },
];

// ── Addition levels (progressive operand ranges) ──

const LEVELS_ADD = [
  { id: 1, title: 'Route 1', subtitle: 'Tiny Sums!', description: 'Add within 5', maxOperand: 5, maxSum: 5, rounds: 8, coinsPerCorrect: 1, bonusCoins: 2, battleAfter: true, theme: 'grass' },
  { id: 2, title: 'Route 2', subtitle: 'Single Digits!', description: 'Add within 10', maxOperand: 5, maxSum: 10, rounds: 8, coinsPerCorrect: 1, bonusCoins: 2, battleAfter: false, theme: 'grass' },
  { id: 3, title: 'Route 3', subtitle: 'Teens!', description: 'Add within 20', maxOperand: 10, maxSum: 20, rounds: 8, coinsPerCorrect: 1, bonusCoins: 4, battleAfter: true, theme: 'water' },
  { id: 4, title: 'Route 4', subtitle: 'Double Up!', description: 'Doubles to 20', maxOperand: 10, maxSum: 20, minOperand: 5, rounds: 10, coinsPerCorrect: 1, bonusCoins: 4, battleAfter: false, theme: 'fire' },
  { id: 5, title: 'Route 5', subtitle: 'Tens!', description: 'Add tens', maxOperand: 30, maxSum: 60, minOperand: 10, rounds: 10, coinsPerCorrect: 2, bonusCoins: 5, battleAfter: true, theme: 'electric' },
  { id: 6, title: 'Route 6', subtitle: 'No Carry!', description: 'Two-digit, no regroup', maxOperand: 50, maxSum: 50, minOperand: 10, rounds: 8, coinsPerCorrect: 2, bonusCoins: 4, battleAfter: false, theme: 'water' },
  { id: 7, title: 'Route 7', subtitle: 'Carry Over!', description: 'Two-digit with regroup', maxOperand: 60, maxSum: 99, minOperand: 15, rounds: 10, coinsPerCorrect: 2, bonusCoins: 6, battleAfter: true, theme: 'psychic' },
  { id: 8, title: 'Route 8', subtitle: 'Big Sums!', description: 'Up to 100', maxOperand: 80, maxSum: 150, minOperand: 20, rounds: 10, coinsPerCorrect: 2, bonusCoins: 7, battleAfter: true, theme: 'ghost' },
  { id: 9, title: 'Route 9', subtitle: 'Hundreds!', description: 'Sums to 200', maxOperand: 99, maxSum: 199, minOperand: 30, rounds: 10, coinsPerCorrect: 3, bonusCoins: 7, battleAfter: true, theme: 'dragon' },
  { id: 10, title: 'Pokemon League', subtitle: 'Addition Master!', description: 'All sums mixed!', maxOperand: 99, maxSum: 199, minOperand: 1, rounds: 15, coinsPerCorrect: 3, bonusCoins: 12, battleAfter: true, theme: 'dragon' },
];

// ── Subtraction levels (progressive operand ranges) ──

const LEVELS_SUB = [
  { id: 1, title: 'Route 1', subtitle: 'Take Away!', description: 'Subtract within 5', maxOperand: 5, maxMinuend: 5, rounds: 8, coinsPerCorrect: 1, bonusCoins: 2, battleAfter: true, theme: 'grass' },
  { id: 2, title: 'Route 2', subtitle: 'Single Digits!', description: 'Subtract within 10', maxOperand: 10, maxMinuend: 10, rounds: 8, coinsPerCorrect: 1, bonusCoins: 2, battleAfter: false, theme: 'grass' },
  { id: 3, title: 'Route 3', subtitle: 'Teens!', description: 'Subtract within 20', maxOperand: 15, maxMinuend: 20, rounds: 8, coinsPerCorrect: 1, bonusCoins: 4, battleAfter: true, theme: 'water' },
  { id: 4, title: 'Route 4', subtitle: 'Crossing Ten!', description: 'Regroup across 10', maxOperand: 15, maxMinuend: 20, minOperand: 3, rounds: 10, coinsPerCorrect: 1, bonusCoins: 4, battleAfter: false, theme: 'fire' },
  { id: 5, title: 'Route 5', subtitle: 'Tens!', description: 'Subtract tens', maxOperand: 50, maxMinuend: 60, minOperand: 10, rounds: 10, coinsPerCorrect: 2, bonusCoins: 5, battleAfter: true, theme: 'electric' },
  { id: 6, title: 'Route 6', subtitle: 'No Borrow!', description: 'Two-digit, no regroup', maxOperand: 40, maxMinuend: 50, minOperand: 10, rounds: 8, coinsPerCorrect: 2, bonusCoins: 4, battleAfter: false, theme: 'water' },
  { id: 7, title: 'Route 7', subtitle: 'Borrow!', description: 'Two-digit with regroup', maxOperand: 50, maxMinuend: 80, minOperand: 15, rounds: 10, coinsPerCorrect: 2, bonusCoins: 6, battleAfter: true, theme: 'psychic' },
  { id: 8, title: 'Route 8', subtitle: 'Big Gaps!', description: 'Up to 100', maxOperand: 70, maxMinuend: 100, minOperand: 10, rounds: 10, coinsPerCorrect: 2, bonusCoins: 7, battleAfter: true, theme: 'ghost' },
  { id: 9, title: 'Route 9', subtitle: 'Hundreds!', description: 'Subtract from 200', maxOperand: 99, maxMinuend: 200, minOperand: 20, rounds: 10, coinsPerCorrect: 3, bonusCoins: 7, battleAfter: true, theme: 'dragon' },
  { id: 10, title: 'Pokemon League', subtitle: 'Subtraction Master!', description: 'All differences mixed!', maxOperand: 99, maxMinuend: 200, minOperand: 1, rounds: 15, coinsPerCorrect: 3, bonusCoins: 12, battleAfter: true, theme: 'dragon' },
];

// ── Mode→Levels lookup ──

const LEVELS_BY_MODE = {
  multiply: LEVELS,
  divide: LEVELS_DIV,
  add: LEVELS_ADD,
  subtract: LEVELS_SUB,
};
